In [64]:
#summary

'''
1. standardize the data
2. cov matrix
3. find out eigen vectors and eigen values (eigen vectors are the vectors which doesn't change the direction even after transformation)
    lets say X is eigen vect then XT = lamda * X where lamba is a scaler or eigen value
4. project the data on to these vectors(or components)

'''



"\n1. standardize the data\n2. cov matrix\n3. find out eigen vectors and eigen values (eigen vectors are the vectors which doesn't change the direction even after transformation)\n    lets say X is eigen vect then XT = lamda * X where lamba is a scaler or eigen value\n4. project the data on to these vectors(or components)\n\n"

In [30]:
#https://plot.ly/ipython-notebooks/principal-component-analysis/

from sklearn.datasets import load_iris
import pandas as pd
from sklearn.preprocessing import StandardScaler
import numpy as np

In [2]:
data = load_iris()
dir(data)

['DESCR', 'data', 'feature_names', 'target', 'target_names']

In [3]:
X = data.data
features = data.feature_names
features

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
X[0:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [5]:
y = data.target

In [6]:
y[0:5]

array([0, 0, 0, 0, 0])

In [7]:
labels = data.target_names
labels

array(['setosa', 'versicolor', 'virginica'], 
      dtype='|S10')

In [8]:
pd.DataFrame(y)[0].unique()

array([0, 1, 2], dtype=int64)

In [9]:
X.shape

(150L, 4L)

In [10]:
y.shape

(150L,)

In [11]:
X = pd.DataFrame(X, columns = features)
y = pd.DataFrame(y, columns = ['class'])

In [12]:
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [13]:
y.head()

class
0      0
1      0
2      0
3      0
4      0

In [14]:
X_std = StandardScaler().fit_transform(X)

In [15]:
X_std[:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [16]:
len(np.cov(X_std)[:1][0])

150

In [17]:
X_std.T.shape

(4L, 150L)

In [22]:
cov_mat = np.cov(X_std.T)

In [24]:
eig_val, eig_vec = np.linalg.eig(cov_mat)

In [25]:
eig_val

array([ 2.93035378,  0.92740362,  0.14834223,  0.02074601])

In [26]:
eig_vec

array([[ 0.52237162, -0.37231836, -0.72101681,  0.26199559],
       [-0.26335492, -0.92555649,  0.24203288, -0.12413481],
       [ 0.58125401, -0.02109478,  0.14089226, -0.80115427],
       [ 0.56561105, -0.06541577,  0.6338014 ,  0.52354627]])

In [28]:
print('size of cov_mat')
print(cov_mat.shape)

print('size of eig vector')
print(eig_vec.shape)

size of cov_mat
(4L, 4L)
size of eig vector
(4L, 4L)


In [29]:
print(cov_mat)
print(eig_vec)

[[ 1.00671141 -0.11010327  0.87760486  0.82344326]
 [-0.11010327  1.00671141 -0.42333835 -0.358937  ]
 [ 0.87760486 -0.42333835  1.00671141  0.96921855]
 [ 0.82344326 -0.358937    0.96921855  1.00671141]]
[[ 0.52237162 -0.37231836 -0.72101681  0.26199559]
 [-0.26335492 -0.92555649  0.24203288 -0.12413481]
 [ 0.58125401 -0.02109478  0.14089226 -0.80115427]
 [ 0.56561105 -0.06541577  0.6338014   0.52354627]]


In [31]:
u,s,v = np.linalg.svd(X_std.T)

In [35]:
print(u)
# print(s.shape)
# print(v.shape)

[[-0.52237162 -0.37231836  0.72101681  0.26199559]
 [ 0.26335492 -0.92555649 -0.24203288 -0.12413481]
 [-0.58125401 -0.02109478 -0.14089226 -0.80115427]
 [-0.56561105 -0.06541577 -0.6338014   0.52354627]]


In [48]:
for ev in eig_vec:
    print(ev)
    
# there is still more to it.. this is only for understanding.

[ 0.52237162 -0.37231836 -0.72101681  0.26199559]
[-0.26335492 -0.92555649  0.24203288 -0.12413481]
[ 0.58125401 -0.02109478  0.14089226 -0.80115427]
[ 0.56561105 -0.06541577  0.6338014   0.52354627]


In [49]:
from sklearn.decomposition import PCA as sklearnPCA
sklearn_pca = sklearnPCA(n_components=2)
Y_sklearn = sklearn_pca.fit_transform(X_std)

In [55]:
print(sklearn_pca.components_)
print(sklearn_pca.explained_variance_)

[[ 0.52237162 -0.26335492  0.58125401  0.56561105]
 [ 0.37231836  0.92555649  0.02109478  0.06541577]]
[ 2.91081808  0.92122093]


In [53]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(X_std)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [57]:
print(pca.components_)
print(pca.explained_variance_)

[[ 0.52237162 -0.26335492  0.58125401  0.56561105]
 [ 0.37231836  0.92555649  0.02109478  0.06541577]]
[ 2.91081808  0.92122093]


In [60]:
import matplotlib.pyplot as plt
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.show()